default: &default
  adapter: postgresql
  encoding: utf8
  username: muktesh
  password: test123
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_dev

production:
  <<: *default
  database: blog_prod

test:
  <<: *default
  database: blog_test